### ISSUE TITLE
Fix RPDE implementation

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#141]
Applying rules:
- Include afterId and afterTimestamp parameters in the next URL (and check the [underlying query](https://www.openactive.io/realtime-paged-data-exchange/#sql-query-example-for-timestamp-id)) ( https://github.com/openactive/developer-microsite/issues/32 ) 
- `afterTimestamp` and `modified` must be integer  ( https://github.com/openactive/developer-microsite/issues/31 ) 

Please do check the underlying query is being implemented correctly: https://www.openactive.io/realtime-paged-data-exchange/#sql-query-example-for-timestamp-id:
```sql
  --include WHERE clause only if @afterTimestamp and @afterId provided
      WHERE (modified = @afterTimestamp
               AND id > @afterId)
         OR (modified > @afterTimestamp)
   ORDER BY modified,
            id
``` 

Not like this:

```javascript
{
  "next": "http://api.letsride.co.uk/public/v1/rides?from=1970-01-01+01%3A02%3A10",
  "items": [
    {
      "state": "updated",
      "id": 2710,
      "kind": "event",
      "modified": "1970-01-01 01:00:01"
      "data": {}
    }
  ],
  "license": "https://creativecommons.org/licenses/by/4.0/"
}
```

Like this:

```javascript
{
  "next": "http://api.letsride.co.uk/public/v1/rides?afterTimestamp=1453931925&afterId=2710",
  "items": [
    {
      "state": "updated",
      "id": 2710,
      "kind": "event",
      "modified": 1453931925,
      "data": {}
    }
  ],
  "license": "https://creativecommons.org/licenses/by/4.0/"
}
```

Note that the `next` URL must include the `id` and the `modified` values from the *last* item in the current page (see here for more details: https://www.openactive.io/realtime-paged-data-exchange/#modified-timestamp-and-id)

**Comment by nickevansuk** [comment]
Just looking at these pages, in order:

- http://lr-api.staging.phoenixdigital.agency/public/v1/rides?afterTimestamp=1511529586&afterId=1805
- http://lr-api.staging.phoenixdigital.agency/public/v1/rides?afterTimestamp=1477924270&afterId=87872
- http://lr-api.staging.phoenixdigital.agency/public/v1/rides?afterTimestamp=1480753800&afterId=88121

Note that the ` ORDER BY modified, id` means that afterTimestamp should be increasing, which they are not.

Also the [second page](http://lr-api.staging.phoenixdigital.agency/public/v1/rides?afterTimestamp=16725225600&afterId=1663) returns `"No ride data found"`.

And [this page](http://lr-api.staging.phoenixdigital.agency/public/v1/rides?afterTimestamp=1480753800&afterId=88121) returns an error.

These indicate that the query has not been implemented correctly. Please check:
```sql
  --include WHERE clause only if @afterTimestamp and @afterId provided
      WHERE (modified = @afterTimestamp
               AND id > @afterId)
         OR (modified > @afterTimestamp)
   ORDER BY modified,
            id
```

**Comment by nickevansuk** [comment]
This is much better! However on [this page](http://lr-api.staging.phoenixdigital.agency/public/v1/rides?afterTimestamp=1285&afterId=1941) the next URL doesn't appear to have an afterTimestamp which is greater than the current value, which suggests the query might still be wrong.

There's now a helpful [video](https://docs.openactive.io/publishing-data/data-feeds/how-a-feed-works) on this page which might be useful (any feedback welcome!)

**Comment by sevenpointsix** [comment]
Sorry @nickevansuk , I've tweaked this now, let me know if it's resolved?

**Comment by nickevansuk** [comment]
That's great, and the validator now works for this since your fix too!

http://validator.openactive.io/rpde?url=http://lr-api.staging.phoenixdigital.agency/public/v1/rides/

Note the issue in the validator relating to the last page - still one to fix there

**Comment by sevenpointsix** [comment]
Hi @nickevansuk . This is the final issue to fix I think! Our final page returns the message 'No ride data found' as a string, which is incorrect. How should we be rendering an empty page of data? Or, should we be excluding the "next" link on a page that has no valid "next" page?

**Comment by sevenpointsix** [comment]
Should be working now I think @nickevansuk ?

**Comment by nickevansuk** [comment]
Just had a quick look... still errors... try running the validator and looking at the bottom of the list of errors?

http://validator.openactive.io/rpde?url=http://lr-api.staging.phoenixdigital.agency/public/v1/rides/

It looks like the last page still doesn't conform (e.g. http://api.letsride.co.uk/public/v1/rides?afterTimestamp=1536246355&afterId=27)

Also if you make the limit of items on each page 500 you'll get less warnings in the validator too.

**Comment by sevenpointsix** [comment]
I can't replicate this @nickevansuk , I only see warnings and no errors. Is it definitely throwing an error for you if you re-run a full validation?

**Comment by sevenpointsix** [comment]
That second link is the live site @nickevansuk , we've fixed it on UAT (http://lr-api.staging.phoenixdigital.agency/public/v1/rides?afterTimestamp=1536246355&afterId=27). I've also fixed the issue found by the validator above.

**Comment by nickevansuk** [comment]
Excellent! Were you able to adjust the page size to 500 too?

**Comment by sevenpointsix** [comment]
The feed should now be returning 500 items per page @nickevansuk

**Comment by nickevansuk** [comment]
http://lr-api.staging.phoenixdigital.agency/public/v1/rides?afterTimestamp=1526246355&afterId=27

Found this just now too...

**Comment by nickevansuk** [comment]
Seems to be resolved
